"""phase1_engine_tables

Revision ID: 202604010001
Revises: 202603250101
Create Date: 2026-04-01 00:01:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202604010001'
down_revision = '202603250101'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brent_crude',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('weekly_change_pct', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brent_crude_recorded_at'), 'brent_crude', ['recorded_at'], unique=False)
    op.create_table('cbn_reserves',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reserves_usd_bn', sa.Float(), nullable=False),
    sa.Column('week_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cbn_reserves_week_of'), 'cbn_reserves', ['week_of'], unique=False)
    op.create_table('fx_rate_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('buying_rate', sa.Float(), nullable=True),
    sa.Column('selling_rate', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('rate_type', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fx_rate_snapshots_pair_source_recorded'), 'fx_rate_snapshots', ['base_currency', 'quote_currency', 'source', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_fx_rate_snapshots_recorded_at'), 'fx_rate_snapshots', ['recorded_at'], unique=False)
    op.create_table('news_headlines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_headlines_published_flagged'), 'news_headlines', ['published_at', 'is_flagged'], unique=False)
    op.create_table('spread_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('official_rate', sa.Float(), nullable=False),
    sa.Column('parallel_rate', sa.Float(), nullable=False),
    sa.Column('bdc_rate', sa.Float(), nullable=True),
    sa.Column('spread_ngn', sa.Float(), nullable=False),
    sa.Column('spread_pct', sa.Float(), nullable=False),
    sa.Column('spread_direction', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spread_snapshots_recorded_at'), 'spread_snapshots', ['recorded_at'], unique=False)
    op.create_table('conversion_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pair', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('base_amount', sa.Float(), nullable=False),
    sa.Column('quote_amount', sa.Float(), nullable=False),
    sa.Column('rate_used', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('followed_recommendation', sa.Boolean(), nullable=True),
    sa.Column('optimal_rate_7d', sa.Float(), nullable=True),
    sa.Column('optimal_amount_7d', sa.Float(), nullable=True),
    sa.Column('lost_amount_7d', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_logs_user_converted'), 'conversion_logs', ['user_id', 'converted_at'], unique=False)
    op.create_table('in_app_notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_in_app_notifications_user_unread'), 'in_app_notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('rate_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pair', sa.String(), nullable=False),
    sa.Column('target_rate', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('rate_source', sa.String(), nullable=False),
    sa.Column('channels', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_triggered', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_rate', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_alerts_pair_active'), 'rate_alerts', ['pair', 'is_active'], unique=False)
    op.create_index(op.f('ix_rate_alerts_user_active'), 'rate_alerts', ['user_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_alerts_user_active'), table_name='rate_alerts')
    op.drop_index(op.f('ix_rate_alerts_pair_active'), table_name='rate_alerts')
    op.drop_table('rate_alerts')
    op.drop_index(op.f('ix_in_app_notifications_user_unread'), table_name='in_app_notifications')
    op.drop_table('in_app_notifications')
    op.drop_index(op.f('ix_conversion_logs_user_converted'), table_name='conversion_logs')
    op.drop_table('conversion_logs')
    op.drop_index(op.f('ix_spread_snapshots_recorded_at'), table_name='spread_snapshots')
    op.drop_table('spread_snapshots')
    op.drop_index(op.f('ix_news_headlines_published_flagged'), table_name='news_headlines')
    op.drop_table('news_headlines')
    op.drop_index(op.f('ix_fx_rate_snapshots_recorded_at'), table_name='fx_rate_snapshots')
    op.drop_index(op.f('ix_fx_rate_snapshots_pair_source_recorded'), table_name='fx_rate_snapshots')
    op.drop_table('fx_rate_snapshots')
    op.drop_index(op.f('ix_cbn_reserves_week_of'), table_name='cbn_reserves')
    op.drop_table('cbn_reserves')
    op.drop_index(op.f('ix_brent_crude_recorded_at'), table_name='brent_crude')
    op.drop_table('brent_crude')
    # ### end Alembic commands ###
